name: Terraform Import - Resource Group

on:
  workflow_dispatch:  # Manual trigger

jobs:
  terraform-import:
    name: 'Import Resource Group'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Import Resource Group
        run: terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/myrg-1

      - name: Terraform Import Resource Group
        run: terraform import azurerm_virtual_network.vnet /subscriptions/07f136e5-d168-4950-a26f-e1a528a1a87c/resourceGroups/myrg-1/providers/Microsoft.Network/virtualNetworks/myVNet
